apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: medecin-africa
  labels:
    app: django-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django
          image: your-registry/medecin-backend:latest  # Update with your container registry
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-secrets
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: DJANGO_SETTINGS_MODULE
              value: "medecin_api.settings.production"
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
  namespace: medecin-africa
spec:
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
