// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
// ignore: avoid_void_async
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4cy3v02c9XBIh0ef33vU6V2NitoGAIvc',
    appId: '1:650459944:web:222da60841ac5b22e7ae1d',
    messagingSenderId: '650459944',
    projectId: 'bana-doctor-4aa85',
    authDomain: 'bana-doctor-4aa85.firebaseapp.com',
    storageBucket: 'bana-doctor-4aa85.firebasestorage.app',
    measurementId: 'G-C8LLCX6E3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGTNhGVWk_KQoTTRi_OiT843QjofnRtIM',
    appId: '1:650459944:android:ce0a1f7b37b7dfa9e7ae1d',
    messagingSenderId: '650459944',
    projectId: 'bana-doctor-4aa85',
    storageBucket: 'bana-doctor-4aa85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcWNEvPlSNUEh7T46qMARfUR8N9-deOXk',
    appId: '1:650459944:ios:2e87ed2de91017d5e7ae1d',
    messagingSenderId: '650459944',
    projectId: 'bana-doctor-4aa85',
    storageBucket: 'bana-doctor-4aa85.firebasestorage.app',
    iosBundleId: 'com.example.medecinMobile',
  );
}
