# This is a template. Replace the values and save as secrets.yaml
# DO NOT commit the actual secrets.yaml file to version control

# PostgreSQL Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: medecin-africa
type: Opaque
data:
  POSTGRES_DB: "b64_encoded_database_name"
  POSTGRES_USER: "b64_encoded_username"
  POSTGRES_PASSWORD: "b64_encoded_password"
  POSTGRES_BACKUP_ENABLED: "dHJ1ZQ=="  # true
  POSTGRES_BACKUP_SCHEDULE: "MAILTO=backup@banadoctor.com 0 2 * * *"
  POSTGRES_BACKUP_S3_BUCKET: "b64_encoded_s3_bucket_name"
  POSTGRES_BACKUP_S3_REGION: "b64_encoded_s3_region"
  POSTGRES_BACKUP_S3_ACCESS_KEY_ID: "b64_encoded_aws_access_key_id"
  POSTGRES_BACKUP_S3_SECRET_ACCESS_KEY: "b64_encoded_aws_secret_access_key"

---
# Django Secrets
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: medecin-africa
type: Opaque
data:
  # Django Core
  SECRET_KEY: "b64_encoded_secret_key"
  DJANGO_ALLOWED_HOSTS: "b64_encoded_allowed_hosts"
  
  # Database
  DB_NAME: "b64_encoded_db_name"
  DB_USER: "b64_encoded_db_user"
  DB_PASSWORD: "b64_encoded_db_password"
  DB_HOST: "postgres.medecin-africa.svc.cluster.local"
  DB_PORT: "NTQzMg=="  # 5432
  
  # Redis
  REDIS_URL: "redis://redis:6379/0"
  
  # JWT Authentication
  JWT_SECRET_KEY: "b64_encoded_jwt_secret_key"
  JWT_ALGORITHM: "SFI1MjU2"  # HS256
  JWT_ACCESS_TOKEN_LIFETIME: "ODY0MDA="  # 1 day in seconds
  JWT_REFRESH_TOKEN_LIFETIME: "NjA0ODAw"  # 7 days in seconds
  
  # API Keys
  FLUTTERWAVE_PUBLIC_KEY: "b64_encoded_flutterwave_public_key"
  FLUTTERWAVE_SECRET_KEY: "b64_encoded_flutterwave_secret_key"
  
  # Firebase Cloud Messaging
  FCM_SERVER_KEY: "b64_encoded_fcm_server_key"
  
  # Email Configuration
  EMAIL_HOST: "b64_encoded_email_host"
  EMAIL_PORT: "NDU3"  # 465
  EMAIL_HOST_USER: "b64_encoded_email_user"
  EMAIL_HOST_PASSWORD: "b64_encoded_email_password"
  EMAIL_USE_TLS: "dHJ1ZQ=="  # true
  EMAIL_USE_SSL: "dHJ1ZQ=="  # true
  DEFAULT_FROM_EMAIL: "b64_encoded_from_email"
  
  # Sentry Configuration
  SENTRY_DSN: "b64_encoded_sentry_dsn"
  SENTRY_ENVIRONMENT: "cHJvZHVjdGlvbg=="  # production
  
  # Prometheus Metrics
  PROMETHEUS_METRICS_ENABLED: "dHJ1ZQ=="  # true
  
  # Security Headers
  SECURE_PROXY_SSL_HEADER: "SFRUUF9YX0ZPUldBUkRFRF9QUk9UTyxodHRwcywgaHR0cA=="
  
  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "aHR0cHM6Ly9hcHAuYmFuYWRvY3Rvci5jb20sIGh0dHBzOi8vYXBpLmJhbmFkb2N0b3IuY29t"
  
  # Backup Configuration
  BACKUP_ENCRYPTION_KEY: "b64_strong_encryption_key"
  
  # Admin Access
  DJANGO_SUPERUSER_USERNAME: "b64_encoded_admin_username"
  DJANGO_SUPERUSER_EMAIL: "b64_encoded_admin_email"
  DJANGO_SUPERUSER_PASSWORD: "b64_encoded_admin_password"
  
  # Rate Limiting
  RATELIMIT_ENABLED: "dHJ1ZQ=="  # true
  RATELIMIT_KEY: "Y2xhc3NfYmFzZWRfdmlld3Mudmlld19zZXRfcmF0ZWxpbWl0"  # class_based_views.view_set_ratelimit
  
  # Security Headers
  SECURE_REFERRER_POLICY: "c2FtZS1vcmlnaW4="  # same-origin
  SECURE_CONTENT_TYPE_NOSNIFF: "dHJ1ZQ=="  # true
  SECURE_BROWSER_XSS_FILTER: "MQ=="  # 1
  X_FRAME_OPTIONS: "REVOWQ=="  # DENY
  
  # Session Security
  SESSION_COOKIE_AGE: "MTIwOTYwMA=="  # 1209600 (2 weeks)
  SESSION_COOKIE_HTTPONLY: "dHJ1ZQ=="  # true
  SESSION_COOKIE_SECURE: "dHJ1ZQ=="  # true
  SESSION_SAVE_EVERY_REQUEST: "dHJ1ZQ=="  # true
  
  # CSRF Protection
  CSRF_COOKIE_SECURE: "dHJ1ZQ=="  # true
  CSRF_COOKIE_HTTPONLY: "dHJ1ZQ=="  # true
  CSRF_TRUSTED_ORIGINS: "aHR0cHM6Ly9hcHAuYmFuYWRvY3Rvci5jb20sIGh0dHBzOi8vYXBpLmJhbmFkb2N0b3IuY29t"  # https://app.banadoctor.com,https://api.banadoctor.com
  
  # HSTS Configuration
  SECURE_HSTS_SECONDS: "MzE1MzYwMDA="  # 31536000 (1 year)
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "dHJ1ZQ=="  # true
  SECURE_HSTS_PRELOAD: "dHJ1ZQ=="  # true
  
  # Content Security Policy
  CSP_DEFAULT_SRC: "J3NlbGYn"  # 'self'
  CSP_SCRIPT_SRC: "J3NlbGYnICd1bnNhZmUtaW5saW5lJyAndW5zYWZlLWV2YWwnIg=="  # 'self' 'unsafe-inline' 'unsafe-eval'
  CSP_STYLE_SRC: "J3NlbGYnICd1bnNhZmUtaW5saW5lJyBodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29t"  # 'self' 'unsafe-inline' https://fonts.googleapis.com
  CSP_IMG_SRC: "J3NlbGYnIGRhdGE6IGJsb2I6IGh0dHBzOi8vKi5iYW5hZG9jdG9yLmNvbQ=="  # 'self' data: blob: https://*.banadoctor.com
  CSP_FONT_SRC: "J3NlbGYnIGh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20gaHR0cHM6Ly9mb250cy5nc3RhdGljLmNvbQ=="  # 'self' https://fonts.googleapis.com https://fonts.gstatic.com
  CSP_CONNECT_SRC: "J3NlbGYnIGh0dHBzOi8vYXBpLmJhbmFkb2N0b3IuY29t"  # 'self' https://api.banadoctor.com
  CSP_FRAME_ANCESTORS: "J25vbmUn"  # 'none'
  
  # Elasticsearch Configuration
  ELASTICSEARCH_HOST: "ZWxhc3RpY3NlYXJjaC1tYXN0ZXIubWVkZWNpbi1hZnJpY2Euc3ZjLmNsdXN0ZXIubG9jYWw="  # elasticsearch-master.medecin-africa.svc.cluster.local
  ELASTICSEARCH_PORT: "OTIwMA=="  # 9200
  ELASTICSEARCH_USE_SSL: "dHJ1ZQ=="  # true
  ELASTICSEARCH_VERIFY_CERTS: "dHJ1ZQ=="  # true
  ELASTICSEARCH_HTTP_AUTH: "YWRtaW46YWRtaW4="  # admin:admin (base64 encoded)
  
  # S3 Storage for Media Files
  AWS_ACCESS_KEY_ID: "b64_encoded_aws_access_key_id"
  AWS_SECRET_ACCESS_KEY: "b64_encoded_aws_secret_access_key"
  AWS_STORAGE_BUCKET_NAME: "b64_encoded_s3_bucket_name"
  AWS_S3_REGION_NAME: "dXMtZWFzdC0x"  # us-east-1
  AWS_S3_CUSTOM_DOMAIN: "czMuYW1hem9uYXdzLmNvbS9iYW5hZG9jdG9yLW1lZGlh"  # s3.amazonaws.com/banadoctor-media
  AWS_DEFAULT_ACL: "cHVibGljLXJlYWQ="  # public-read
  AWS_S3_OBJECT_PARAMETERS: "eyJBY2wiOiJwdWJsaWMtcmVhZCJ9"  # {"Acl": "public-read"}
  
  # Backup Configuration
  BACKUP_S3_BUCKET: "b64_encoded_backup_bucket_name"
  BACKUP_S3_REGION: "dXMtZWFzdC0x"  # us-east-1
  BACKUP_ENCRYPTION_KEY: "b64_strong_encryption_key"
  
  # Monitoring & Alerting
  PROMETHEUS_ENABLED: "dHJ1ZQ=="  # true
  PROMETHEUS_PORT: "OTAwMA=="  # 9000
  
  # Alert Manager Configuration
  ALERTMANAGER_WEBHOOK_URL: "b64_encoded_alertmanager_webhook_url"
  
  # Slack Webhook for Alerts
  SLACK_WEBHOOK_URL: "b64_encoded_slack_webhook_url"
  
  # Email for Critical Alerts
  ALERT_EMAIL: "YWxlcnRzQGJhbmFkb2N0b3IuY29t"  # alerts@banadoctor.com
  
  # Maintenance Mode
  MAINTENANCE_MODE: "ZmFsc2U="  # false
  
  # Feature Flags
  FEATURE_APPOINTMENT_SCHEDULING: "dHJ1ZQ=="  # true
  FEATURE_ONLINE_PAYMENTS: "dHJ1ZQ=="  # true
  FEATURE_VIDEO_CONSULTATION: "dHJ1ZQ=="  # true
  FEATURE_PATIENT_PORTAL: "dHJ1ZQ=="  # true
  FEATURE_DOCTOR_DASHBOARD: "dHJ1ZQ=="  # true
  
  # API Rate Limiting
  API_RATE_LIMIT: "MTAwMA=="  # 1000
  API_RATE_LIMIT_PERIOD: "MzYwMA=="  # 3600 (1 hour)
  
  # Security Headers
  SECURE_REFERRER_POLICY: "c2FtZS1vcmlnaW4="  # same-origin
  SECURE_CONTENT_TYPE_NOSNIFF: "dHJ1ZQ=="  # true
  SECURE_BROWSER_XSS_FILTER: "MQ=="  # 1
  X_FRAME_OPTIONS: "REVOWQ=="  # DENY
  
  # Session Security
  SESSION_COOKIE_AGE: "MTIwOTYwMA=="  # 1209600 (2 weeks)
  SESSION_COOKIE_HTTPONLY: "dHJ1ZQ=="  # true
  SESSION_COOKIE_SECURE: "dHJ1ZQ=="  # true
  SESSION_SAVE_EVERY_REQUEST: "dHJ1ZQ=="  # true
  
  # CSRF Protection
  CSRF_COOKIE_SECURE: "dHJ1ZQ=="  # true
  CSRF_COOKIE_HTTPONLY: "dHJ1ZQ=="  # true
  CSRF_TRUSTED_ORIGINS: "aHR0cHM6Ly9hcHAuYmFuYWRvY3Rvci5jb20sIGh0dHBzOi8vYXBpLmJhbmFkb2N0b3IuY29t"  # https://app.banadoctor.com,https://api.banadoctor.com
  
  # HSTS Configuration
  SECURE_HSTS_SECONDS: "MzE1MzYwMDA="  # 31536000 (1 year)
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "dHJ1ZQ=="  # true
  SECURE_HSTS_PRELOAD: "dHJ1ZQ=="  # true
  
  # Content Security Policy
  CSP_DEFAULT_SRC: "J3NlbGYn"  # 'self'
  CSP_SCRIPT_SRC: "J3NlbGYnICd1bnNhZmUtaW5saW5lJyAndW5zYWZlLWV2YWwnIg=="  # 'self' 'unsafe-inline' 'unsafe-eval'
  CSP_STYLE_SRC: "J3NlbGYnICd1bnNhZmUtaW5saW5lJyBodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29t"  # 'self' 'unsafe-inline' https://fonts.googleapis.com
  CSP_IMG_SRC: "J3NlbGYnIGRhdGE6IGJsb2I6IGh0dHBzOi8vKi5iYW5hZG9jdG9yLmNvbQ=="  # 'self' data: blob: https://*.banadoctor.com
  CSP_FONT_SRC: "J3NlbGYnIGh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20gaHR0cHM6Ly9mb250cy5nc3RhdGljLmNvbQ=="  # 'self' https://fonts.googleapis.com https://fonts.gstatic.com
  CSP_CONNECT_SRC: "J3NlbGYnIGh0dHBzOi8vYXBpLmJhbmFkb2N0b3IuY29t"  # 'self' https://api.banadoctor.com
  CSP_FRAME_ANCESTORS: "J25vbmUn"  # 'none'
