filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata: ~

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_kubernetes_metadata: ~

# Configure what to do when encountering errors
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

setup.ilm.enabled: false
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  indices:
    - index: "filebeat-django-%{+yyyy.MM.dd}"
      when.equals:
        docker.container.labels.com_docker_compose_service: django
    - index: "filebeat-nginx-%{+yyyy.MM.dd}"
      when.equals:
        docker.container.labels.com_docker_compose_service: nginx
    - index: "filebeat-other-%{+yyyy.MM.dd}"

setup.dashboards.enabled: true
setup.kibana:
  host: "http://kibana:5601"
