apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: medecin-africa
  labels:
    app: frontend-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: nextjs
          image: your-registry/medecin-frontend:latest  # Update with your container registry
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: django-secrets
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.medecin.africa"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
  namespace: medecin-africa
spec:
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
