apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: medecin-africa
data:
  # Configuration Django
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SETTINGS_MODULE: "medecin_api.settings.production"
  
  # Configuration CORS
  CORS_ALLOWED_ORIGINS: "https://app.banadoctor.com,https://api.banadoctor.com"
  
  # Configuration des timeouts
  REQUEST_TIMEOUT: "30"
  
  # Configuration Elasticsearch
  ELASTICSEARCH_HOST: "elasticsearch.medecin-africa.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200"
  
  # Configuration des URLs
  FRONTEND_URL: "https://app.banadoctor.com"
  API_URL: "https://api.banadoctor.com"
  
  # Configuration des logs
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Configuration des sauvegardes
  BACKUP_ENABLED: "true"
  BACKUP_RETENTION_DAYS: "30"
  
  # Configuration des alertes
  ALERTING_ENABLED: "true"
  ALERTING_EMAIL: "alerts@banadoctor.com"
  
  # Configuration des ressources
  WORKER_CONCURRENCY: "4"
  WORKER_MAX_REQUESTS: "1000"
  WORKER_MAX_REQUESTS_JITTER: "50"
  
  # Configuration du cache
  CACHE_TIMEOUT: "3600"
  SESSION_COOKIE_AGE: "1209600"  # 2 semaines
  
  # Configuration des tâches asynchrones
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  CELERY_WORKER_CONCURRENCY: "4"
  
  # Configuration des limites de taux
  RATE_LIMIT: "1000/hour"
  
  # Configuration de la sécurité
  SECURE_SSL_REDIRECT: "True"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  SECURE_BROWSER_XSS_FILTER: "True"
  X_FRAME_OPTIONS: "DENY"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
  
  # Configuration des en-têtes de sécurité
  SECURE_HSTS_SECONDS: "31536000"  # 1 an
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  
  # Configuration des cookies
  SESSION_COOKIE_HTTPONLY: "True"
  SESSION_COOKIE_SAMESITE: "Lax"
  
  # Configuration CSP (Content Security Policy)
  CSP_DEFAULT_SRC: "'self'"
  CSP_SCRIPT_SRC: "'self' 'unsafe-inline' 'unsafe-eval'"
  CSP_STYLE_SRC: "'self' 'unsafe-inline'"
  CSP_IMG_SRC: "'self' data: blob: https:"
