# Generated by Django 4.2.22 on 2025-06-14 16:00

import datetime
from django.db import migrations, models


def set_created_at_default(apps, schema_editor):
    """Set a default created_at for existing records"""
    DoctorEducation = apps.get_model('users', 'DoctorEducation')
    # Update all existing records with current timestamp
    for education in DoctorEducation.objects.all():
        education.created_at = datetime.datetime.now()
        education.save(update_fields=['created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_doctoravailability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreducation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.RunPython(set_created_at_default, reverse_code=migrations.RunPython.noop),
    ]
