# Generated by Django 4.2.22 on 2025-06-14 16:01

from django.db import migrations, models
import django.utils.timezone


def set_updated_at_default(apps, schema_editor):
    """Set updated_at to current time for existing records"""
    DoctorEducation = apps.get_model('users', 'DoctorEducation')
    # Update all existing records with current timestamp
    for education in DoctorEducation.objects.all():
        education.updated_at = django.utils.timezone.now()
        education.save(update_fields=['updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_created_at_to_doctoreducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_updated_at_default, reverse_code=migrations.RunPython.noop),
    ]
