# Generated by Django 4.2.22 on 2025-06-16 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctorprofile_alter_doctoreducation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor_verified',
            field=models.BooleanField(default=False, help_text='Doctor verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.CreateModel(
            name='DoctorVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license', 'Medical License'), ('diploma', 'Medical Diploma'), ('id_card', 'National ID Card'), ('certificate', 'Specialty Certificate'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to='doctor_verification/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Verification Document',
                'verbose_name_plural': 'Doctor Verification Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
